# Generated by Django 2.1.7 on 2019-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffractionGrating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('Beyond_yellow1', models.CharField(max_length=30, verbose_name='黄外光&phi;<sub>1</sub>')),
                ('Beyond_yellow2', models.CharField(max_length=30, verbose_name='黄外光&phi;<sub>2</sub>')),
                ('Beyond_yellow3', models.CharField(max_length=30, verbose_name="黄外光&phi;'<sub>1</sub>")),
                ('Beyond_yellow4', models.CharField(max_length=30, verbose_name="黄外光&phi;'<sub>2</sub>")),
                ('Inside_yellow1', models.CharField(max_length=30, verbose_name='黄内光&phi;<sub>1</sub>')),
                ('Inside_yellow2', models.CharField(max_length=30, verbose_name='黄内光&phi;<sub>2</sub>')),
                ('Inside_yellow3', models.CharField(max_length=30, verbose_name="黄内光&phi;'<sub>1</sub>")),
                ('Inside_yellow4', models.CharField(max_length=30, verbose_name="黄内光&phi;'<sub>2</sub>")),
                ('green1', models.CharField(max_length=30, verbose_name='绿光&phi;<sub>1</sub>')),
                ('green2', models.CharField(max_length=30, verbose_name='绿光&phi;<sub>2</sub>')),
                ('green3', models.CharField(max_length=30, verbose_name="绿光&phi;'<sub>1</sub>")),
                ('green4', models.CharField(max_length=30, verbose_name="绿光&phi;'<sub>2</sub>")),
                ('blue1', models.CharField(max_length=30, verbose_name='蓝光&phi;<sub>1</sub>')),
                ('blue2', models.CharField(max_length=30, verbose_name='蓝光&phi;<sub>2</sub>')),
                ('blue3', models.CharField(max_length=30, verbose_name="蓝光&phi;'<sub>1</sub>")),
                ('blue4', models.CharField(max_length=30, verbose_name="蓝光&phi;'<sub>2</sub>")),
                ('N', models.IntegerField(verbose_name='光栅有效面积内狭缝总数')),
                ('Beyond_yellow_k', models.IntegerField(verbose_name='黄内光光谱级次')),
                ('Inside_yellow_k', models.IntegerField(verbose_name='黄外光光谱级次')),
                ('green_k', models.IntegerField(verbose_name='绿光光谱级次')),
                ('blue_k', models.IntegerField(verbose_name='蓝光光谱级次')),
                ('d', models.IntegerField(verbose_name='光栅常数')),
                ('Beyond_yellow', models.CharField(max_length=30, verbose_name='黄外光衍射角')),
                ('Inside_yellow', models.CharField(max_length=30, verbose_name='黄内光衍射角')),
                ('green', models.CharField(max_length=30, verbose_name='绿光衍射角')),
                ('blue', models.CharField(max_length=30, verbose_name='蓝光衍射角')),
                ('Beyond_yellow_lambda', models.IntegerField(verbose_name='黄外光波长')),
                ('Inside_yellow_lambda', models.IntegerField(verbose_name='黄内光波长')),
                ('green_lambda', models.IntegerField(verbose_name='绿光波长')),
                ('blue_lambda', models.IntegerField(verbose_name='蓝光波长')),
                ('Beyond_yellow_D', models.IntegerField(verbose_name='黄外光色散率')),
                ('Inside_yellow_D', models.IntegerField(verbose_name='黄内光色散率')),
                ('green_D', models.IntegerField(verbose_name='绿光色散率')),
                ('blue_D', models.IntegerField(verbose_name='蓝光色散率')),
                ('Beyond_yellow_R', models.IntegerField(verbose_name='黄外光分辨本领')),
                ('Inside_yellow_R', models.IntegerField(verbose_name='黄内光分辨本领')),
                ('green_R', models.IntegerField(verbose_name='绿光分辨本领')),
                ('blue_R', models.IntegerField(verbose_name='蓝光分辨本领')),
                ('Beyond_yellow_delta_lambda', models.IntegerField(verbose_name='黄外光波长差')),
                ('Inside_yellow_delta_lambda', models.IntegerField(verbose_name='黄外光波长差')),
                ('green_delta_lambda', models.IntegerField(verbose_name='黄外光波长差')),
                ('blue_delta_lambda', models.IntegerField(verbose_name='黄外光波长差')),
            ],
            options={
                'verbose_name': '衍射光栅',
                'verbose_name_plural': '衍射光栅',
            },
        ),
    ]
