# Generated by Django 2.1.7 on 2019-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiffractionGrating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Beyond_yellow_D',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光色散率'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Beyond_yellow_R',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光分辨本领'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Beyond_yellow_delta_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光波长差'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Beyond_yellow_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光波长'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Inside_yellow_D',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄内光色散率'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Inside_yellow_R',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄内光分辨本领'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Inside_yellow_delta_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光波长差'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='Inside_yellow_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄内光波长'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='blue_D',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='蓝光色散率'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='blue_R',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='蓝光分辨本领'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='blue_delta_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光波长差'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='blue_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='蓝光波长'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='green_D',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='绿光色散率'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='green_R',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='绿光分辨本领'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='green_delta_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='黄外光波长差'),
        ),
        migrations.AlterField(
            model_name='diffractiongrating',
            name='green_lambda',
            field=models.DecimalField(decimal_places=7, max_digits=15, verbose_name='绿光波长'),
        ),
    ]
