# Generated by Django 2.1.7 on 2019-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalConductivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('Tp_1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp1')),
                ('Tp_2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp2')),
                ('Tp_3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp3')),
                ('Tp_4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp4')),
                ('Tp_5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp5')),
                ('Tp_6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp6')),
                ('Tp_7', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp7')),
                ('Tp_8', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp8')),
                ('Tp_9', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp9')),
                ('Tp_10', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp10')),
                ('Tp_11', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp11')),
                ('Tp_12', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp12')),
                ('Tp_13', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp13')),
                ('Tp_14', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp14')),
                ('Tp_15', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp15')),
                ('Tp_16', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp16')),
                ('Tp_17', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp17')),
                ('Tp_18', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp18')),
                ('Tp_19', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp19')),
                ('Tp_20', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Tp20')),
                ('hb_1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度1')),
                ('hb_2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度2')),
                ('hb_3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度3')),
                ('hb_4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度4')),
                ('hb_5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度5')),
                ('hb_6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='样品厚度6')),
                ('Ta', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='加热盘稳态')),
                ('Tp', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘稳态')),
                ('D1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径1')),
                ('D2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径2')),
                ('D3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径3')),
                ('D4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径4')),
                ('D5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径5')),
                ('D6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘直径6')),
                ('D', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='平均直径')),
                ('m', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热盘质量')),
                ('c', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='比热容')),
                ('space1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='散热时间间隔')),
                ('space2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='加热时间间隔')),
                ('p1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='二次方程')),
                ('p2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='导函数')),
                ('t', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='斜率')),
                ('img1', models.ImageField(upload_to='images/ThermalConductivity/%Y/%m/%d', verbose_name='升温曲线')),
                ('img2', models.ImageField(upload_to='images/ThermalConductivity/%Y/%m/%d', verbose_name='降温曲线')),
                ('k', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='导热系数')),
            ],
            options={
                'verbose_name': '非良导体热导率实验',
                'verbose_name_plural': '非良导体热导率实验',
            },
        ),
    ]
