# Generated by Django 2.1.7 on 2019-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThermalConductivity', '0002_auto_20190307_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalconductivity',
            name='img10',
            field=models.ImageField(blank=True, null=True, upload_to='images/ThermalConductivity/%Y/%m/%d', verbose_name='升温曲线'),
        ),
        migrations.AddField(
            model_name='thermalconductivity',
            name='img20',
            field=models.ImageField(blank=True, null=True, upload_to='images/ThermalConductivity/%Y/%m/%d', verbose_name='降温曲线'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp1'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_10',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp10'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_11',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp11'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_12',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp12'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_13',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp13'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_14',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp14'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_15',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp15'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_16',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp16'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_17',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp17'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_18',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp18'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_19',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp19'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp2'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_20',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp20'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp3'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_4',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp4'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_5',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp5'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_6',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp6'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_7',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp7'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_8',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp8'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='Tp_9',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Tp9'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='img1',
            field=models.CharField(max_length=100, verbose_name='升温曲线'),
        ),
        migrations.AlterField(
            model_name='thermalconductivity',
            name='img2',
            field=models.CharField(max_length=100, verbose_name='降温曲线'),
        ),
    ]
