# Generated by Django 2.1.7 on 2019-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Michelson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('one', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>1</sub>(mm)')),
                ('two', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>2</sub>(mm)')),
                ('three', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>3</sub>(mm)')),
                ('four', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>4</sub>(mm)')),
                ('five', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>5</sub>(mm)')),
                ('six', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>6</sub>(mm)')),
                ('seven', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>7</sub>(mm)')),
                ('eight', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>8</sub>(mm)')),
                ('nine', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>9</sub>(mm)')),
                ('ten', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>10</sub>(mm)')),
                ('eleven', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>11</sub>(mm)')),
                ('twelfth', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d<sub>12</sub>(mm)')),
                ('seven_one', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>7</sub>-d<sub>1</sub>(mm)')),
                ('eight_two', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>8</sub>-d<sub>2</sub>(mm)')),
                ('nine_three', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>9</sub>-d<sub>3</sub>(mm)')),
                ('ten_four', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>10</sub>-d<sub>4</sub>(mm)')),
                ('eleven_five', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>11</sub>-d<sub>5</sub>(mm)')),
                ('twelfth_six', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d=d<sub>12</sub>-d<sub>6</sub>(mm)')),
                ('deltad', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='d的平均值')),
                ('deltadD', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='△d的不确定度')),
                ('lambda_avg', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='&#923;平均值')),
                ('deltadlambda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='&#923;不确定度')),
                ('E', models.CharField(max_length=20, verbose_name='相对不确定度')),
                ('Instrumenttolerance', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='仪器允差')),
            ],
            options={
                'verbose_name': '迈克尔逊干涉仪实验',
            },
        ),
    ]
