# Generated by Django 2.1.7 on 2019-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Michelson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michelson',
            name='Instrumenttolerance',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='仪器允差'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltad',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d的平均值'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltadD',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d的不确定度'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltadlambda',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='&#923;不确定度'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='eight',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>8</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='eight_two',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>8</sub>-d<sub>2</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='eleven',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>11</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='eleven_five',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>11</sub>-d<sub>5</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='five',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>5</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='four',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>4</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='lambda_avg',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='&#923;平均值'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='nine',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>9</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='nine_three',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>9</sub>-d<sub>3</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='one',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>1</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='seven',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>7</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='seven_one',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>7</sub>-d<sub>1</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='six',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>6</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='ten',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>10</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='ten_four',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>10</sub>-d<sub>4</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='three',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>3</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='twelfth',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>12</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='twelfth_six',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d=d<sub>12</sub>-d<sub>6</sub>(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='two',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d<sub>2</sub>(mm)'),
        ),
    ]
