# Generated by Django 2.1.7 on 2019-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Michelson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='michelson',
            options={'verbose_name': '迈克尔逊干涉仪实验', 'verbose_name_plural': '迈克尔逊干涉仪实验'},
        ),
        migrations.AlterField(
            model_name='michelson',
            name='Instrumenttolerance',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='仪器允差(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltad',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='d的平均值(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltadD',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='△d的不确定度(mm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='deltadlambda',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='&#923;不确定度(nm)'),
        ),
        migrations.AlterField(
            model_name='michelson',
            name='lambda_avg',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='&#923;平均值(nm)'),
        ),
    ]
