# Generated by Django 2.1.7 on 2019-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('l5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第5个读数(mm)')),
                ('l6', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第6个读数(mm)')),
                ('l7', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第7个读数(mm)')),
                ('l8', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第8个读数(mm)')),
                ('l9', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第9个读数(mm)')),
                ('l10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第10个读数(mm)')),
                ('l25', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第25个读数(mm)')),
                ('l26', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第26个读数(mm)')),
                ('l27', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第27个读数(mm)')),
                ('l28', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第28个读数(mm)')),
                ('l29', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第29个读数(mm)')),
                ('l30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第30个读数(mm)')),
                ('r5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第5个读数(mm)')),
                ('r6', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第6个读数(mm)')),
                ('r7', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第7个读数(mm)')),
                ('r8', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第8个读数(mm)')),
                ('r9', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第9个读数(mm)')),
                ('r10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第10个读数(mm)')),
                ('r25', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第25个读数(mm)')),
                ('r26', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第26个读数(mm)')),
                ('r27', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第27个读数(mm)')),
                ('r28', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第28个读数(mm)')),
                ('r29', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第29个读数(mm)')),
                ('r30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第30个读数(mm)')),
                ('d5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第5个环直径(mm)')),
                ('d6', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第6个环直径(mm)')),
                ('d7', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第7个环直径(mm)')),
                ('d8', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第8个环直径(mm)')),
                ('d9', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第9个环直径(mm)')),
                ('d10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第10个环直径(mm)')),
                ('d25', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第25个环直径(mm)')),
                ('d26', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第26个环直径(mm)')),
                ('d27', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第27个环直径(mm)')),
                ('d28', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第28个环直径(mm)')),
                ('d29', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第29个环直径(mm)')),
                ('d30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第30个环直径(mm)')),
                ('r30_10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='30与10所求得的曲率半径')),
                ('r29_9', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='29与9所求得的曲率半径')),
                ('r28_8', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='28与8所求得的曲率半径')),
                ('r27_7', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='27与7所求得的曲率半径')),
                ('r26_6', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='26与6所求得的曲率半径')),
                ('r25_5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='25与5所求得的曲率半径')),
                ('value30_10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='30与10半径平方差')),
                ('value29_9', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='29与9半径平方差')),
                ('value28_8', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='28与8半径平方差')),
                ('value27_7', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='27与7半径平方差')),
                ('value26_6', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='26与6半径平方差')),
                ('value25_5', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='25与5半径平方差')),
                ('Instrumenttolerance', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='仪器允差(mm)')),
                ('lamda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='波长(nm)')),
                ('uncertainty', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='不确定度(m)')),
                ('anwser', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='曲率半径(m)')),
            ],
            options={
                'verbose_name': '牛顿环实验',
                'verbose_name_plural': '牛顿环实验',
            },
        ),
    ]
