# Generated by Django 2.1.7 on 2019-02-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('l10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第10个读数(mm)')),
                ('l11', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第11个读数(mm)')),
                ('l12', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第12个读数(mm)')),
                ('l13', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第13个读数(mm)')),
                ('l14', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第14个读数(mm)')),
                ('l15', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第15个读数(mm)')),
                ('l30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第30个读数(mm)')),
                ('l31', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第31个读数(mm)')),
                ('l32', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第32个读数(mm)')),
                ('l33', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第33个读数(mm)')),
                ('l34', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第34个读数(mm)')),
                ('l35', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='左边第35个读数(mm)')),
                ('r10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第10个读数(mm)')),
                ('r11', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第11个读数(mm)')),
                ('r12', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第12个读数(mm)')),
                ('r13', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第13个读数(mm)')),
                ('r14', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第14个读数(mm)')),
                ('r15', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第15个读数(mm)')),
                ('r30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第30个读数(mm)')),
                ('r31', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第31个读数(mm)')),
                ('r32', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第32个读数(mm)')),
                ('r33', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第33个读数(mm)')),
                ('r34', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第34个读数(mm)')),
                ('r35', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='右边第35个读数(mm)')),
                ('d10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第10个环直径(mm)')),
                ('d11', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第11个环直径(mm)')),
                ('d12', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第12个环直径(mm)')),
                ('d13', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第13个环直径(mm)')),
                ('d14', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第14个环直径(mm)')),
                ('d15', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第15个环直径(mm)')),
                ('d30', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第30个环直径(mm)')),
                ('d31', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第31个环直径(mm)')),
                ('d32', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第32个环直径(mm)')),
                ('d33', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第33个环直径(mm)')),
                ('d34', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第34个环直径(mm)')),
                ('d35', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='第35个环直径(mm)')),
                ('r35_15', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='35与15所得的曲率半径')),
                ('r34_14', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='34与14所得的曲率半径')),
                ('r33_13', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='33与13所得的曲率半径')),
                ('r32_12', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='32与12所得的曲率半径')),
                ('r31_11', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='31与11所得的曲率半径')),
                ('r30_10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='30与10所得的曲率半径')),
                ('value35_15', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='35与15半径平方差')),
                ('value34_14', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='34与14半径平方差')),
                ('value33_13', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='33与13半径平方差')),
                ('value32_12', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='32与12半径平方差')),
                ('value31_11', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='31与11半径平方差')),
                ('value30_10', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='30与10半径平方差')),
                ('Instrumenttolerance', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='仪器允差(mm)')),
                ('lamda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='波长(nm)')),
                ('uncertainty', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='不确定度(m)')),
                ('anwser', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='曲率半径(m)')),
            ],
            options={
                'verbose_name': '牛顿环实验',
                'verbose_name_plural': '牛顿环实验',
            },
        ),
    ]
