# Generated by Django 2.1.7 on 2019-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticYooungModulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n0', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值0')),
                ('n1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值1')),
                ('n2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值2')),
                ('n3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值3')),
                ('n4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值4')),
                ('n5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值5')),
                ('n6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值6')),
                ('n7', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='增荷值7')),
                ('n_0', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值0')),
                ('n_1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值1')),
                ('n_2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值2')),
                ('n_3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值3')),
                ('n_4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值4')),
                ('n_5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值5')),
                ('n_6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值6')),
                ('n_7', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='减荷值7')),
                ('d1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径1')),
                ('d2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径2')),
                ('d3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径3')),
                ('d4', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径4')),
                ('d5', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径5')),
                ('d6', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='直径6')),
                ('d_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='平均直径')),
                ('L', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='金属丝原长')),
                ('D', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='光杆与望远镜镜尺距离')),
                ('K', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='光光杆常数')),
                ('delta_L', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='金属丝原长不确定度')),
                ('delta_D', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='光杆与望远镜镜尺距离不确定度')),
                ('delta_K', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='光光杆常数不确定度')),
                ('micrometer', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='螺旋测微器允差')),
                ('verniercaliper', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='游标卡尺允差')),
                ('n0_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值0')),
                ('n1_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值1')),
                ('n2_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值2')),
                ('n3_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值3')),
                ('n4_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值4')),
                ('n5_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值5')),
                ('n6_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值6')),
                ('n7_avg', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='差值7')),
                ('n4_0', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='4与0座差')),
                ('n5_1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='5与1座差')),
                ('n6_2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='6与2座差')),
                ('n7_3', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='7与3座差')),
                ('ln', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='四个砝码铁丝拉伸量△l的光杆放大量')),
                ('delta_dn', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='d的不确定度')),
                ('delta_ln', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='l的不确定度')),
                ('E', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='杨氏模量')),
                ('delta_E', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='不确定度')),
                ('relative_E', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='相对不确定度')),
            ],
        ),
    ]
