# Generated by Django 2.1.7 on 2019-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticYoungModulus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticyooungmodulus',
            options={'verbose_name': '杨氏静态模量实验', 'verbose_name_plural': '杨氏静态模量实验'},
        ),
        migrations.AddField(
            model_name='staticyooungmodulus',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='学生编号'),
        ),
        migrations.AddField(
            model_name='staticyooungmodulus',
            name='user_name',
            field=models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名'),
        ),
        migrations.AddField(
            model_name='staticyooungmodulus',
            name='user_num',
            field=models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号'),
        ),
        migrations.AlterField(
            model_name='staticyooungmodulus',
            name='relative_E',
            field=models.CharField(max_length=20, verbose_name='相对不确定度'),
        ),
    ]
