# Generated by Django 2.1.7 on 2019-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='学生编号')),
                ('user_name', models.CharField(blank=True, default='李华', max_length=20, null=True, verbose_name='学生姓名')),
                ('user_num', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='学生学号')),
                ('phi1_1', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_1', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi3_1', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi4_1', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi1_2', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_2', models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>')),
                ('phi3_2', models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>")),
                ('phi4_2', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi1_3', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_3', models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>')),
                ('phi3_3', models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>")),
                ('phi4_3', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi1_4', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_4', models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>')),
                ('phi3_4', models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>")),
                ('phi4_4', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi1_5', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_5', models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>')),
                ('phi3_5', models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>")),
                ('phi4_5', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('phi1_6', models.CharField(max_length=30, verbose_name='&phi;<sub>1</sub>')),
                ('phi2_6', models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>')),
                ('phi3_6', models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>")),
                ('phi4_6', models.CharField(max_length=30, verbose_name="&phi;'<sub>2</sub>")),
                ('Instrumenttolerance', models.CharField(default="1'", max_length=30, verbose_name='分光计仪器允差')),
                ('phi1', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('phi2', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('phi3', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('phi4', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('phi5', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('phi6', models.CharField(max_length=30, verbose_name="1/2(|&phi;<sub>1</sub>-&phi;<sub>2</sub>|+|&phi;'<sub>1</sub>-&phi;'<sub>2</sub>|)")),
                ('alpha', models.CharField(max_length=30, verbose_name='顶角')),
                ('phiba', models.CharField(max_length=30, verbose_name='角度平均值')),
                ('delta', models.CharField(max_length=30, verbose_name='不确定度')),
            ],
            options={
                'verbose_name': '分光计的调整与使用',
                'verbose_name_plural': '分光计的调整与使用',
            },
        ),
    ]
