# Generated by Django 2.1.7 on 2019-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spectrometer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrometer',
            name='phi2_1',
            field=models.CharField(max_length=30, verbose_name='&phi;<sub>2</sub>'),
        ),
        migrations.AlterField(
            model_name='spectrometer',
            name='phi3_1',
            field=models.CharField(max_length=30, verbose_name="&phi;'<sub>1</sub>"),
        ),
    ]
